version: '3.8'

services:
  app:
    image: yaront111/zesty111:latest
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      CONTAINER_REGISTRY: https://hub.docker.com/repository/docker/yaront111/zesty111
    env_file:
      - ./App/app/dev/.env
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  dynamodb:
    image: zestyco/dynamodb-challenge:amd
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

networks:
  backend:
    driver: overlay
